guests = ["Bob", "Paul", "Nkosi"]
print(f"{guests[0]}, you are invited to dinner")
print(f"{guests[1]}, you are invited to dinner")
print(f"{guests[2]}, you are invited to dinner")
print(guests[1])
guests.remove("Paul")
guests.insert(1, "Alice")
print(f"{guests[0]}, you are invited to dinner")
print(f"{guests[1]}, you are invited to dinner")
print(f"{guests[2]}, you are invited to dinner")
print("We've found a bigger table!")
guests.insert(0, "Gaia")
guests.insert(2, "Zeus")
guests.append("Apollo")
print(f"{guests[0]}, you are invited to dinner")
print(f"{guests[1]}, you are invited to dinner")
print(f"{guests[2]}, you are invited to dinner")
print(f"{guests[4]}, you are invited to dinner")
print(f"{guests[5]}, you are invited to dinner")
popped_guest = guests.pop()
print(f"{popped_guest}, you aint comin!")
popped_guest = guests.pop()
print(f"{popped_guest}, you aint comin!")
popped_guest = guests.pop()
print(f"{popped_guest}, you aint comin!")
popped_guest = guests.pop()
print(f"{popped_guest}, you aint comin!")
print(f"{guests[0]}, you are invited to dinner")
print(f"{guests[1]}, you are invited to dinner")
del guests[0]
del guests[0]
print(guests)